version: '3.8'

services:
  flask-app:
    build: .
    container_name: project-manager-container
    volumes:
      - ./data/uploads:/app/app/static/uploads
      - ./data/db:/app/db
      # - ./letsencrypt:/etc/letsencrypt
    ports:
      - "8080:8080"
    command: ["/bin/bash", "./start.sh"]
    #networks:
    #  - network_name

#networks:
#  network_name:
#    driver: bridge
#    external: true
