"""Added starred column to projects table

Revision ID: 09ab2156e78e
Revises: b0fea1968e3f
Create Date: 2025-02-21 12:18:37.323678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ab2156e78e'
down_revision = 'b0fea1968e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starred', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('starred')

    # ### end Alembic commands ###
